# Generated by Django 5.2.1 on 2026-04-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['serial_number']},
        ),
        migrations.AddField(
            model_name='question',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
